<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\PC\source\repos\BlackJack\Application\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\PC\source\repos\BlackJack\Application\.editorconfig" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console" Version="0.56.0"/>
    </ItemGroup>

</Project>
